schema:
  - schema.graphql # 👈 run "nx run infra:graphql-transform" for the AppSync GraphQL schema to be generated
  - appsync.graphql # 👈 used by @graphql-codegen/cli to handle AppSync custom scalars

generates:
  ./libs/data-types/src/lib/types.ts: # 👈 generate the GraphQL types under the data-types lib so that it is accessible from both backend and frontend apps
    plugins:
      - typescript

config:
  scalars:
    AWSJSON: string
    AWSDate: string
    AWSTime: string
    AWSDateTime: string
    AWSTimestamp: number
    AWSEmail: string
    AWSURL: string
    AWSPhone: string
    AWSIPAddress: string
